// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/CalmMeditationNotificationCenter-oBZP_C/App.tsx": () => import("../components/mockups/templates/CalmMeditationNotificationCenter-oBZP_C/App.tsx"),
  "./components/mockups/templates/SeveranceDinnerPartyInvite-reGH7E/DinnerPartyPosterSeverance.tsx": () => import("../components/mockups/templates/SeveranceDinnerPartyInvite-reGH7E/DinnerPartyPosterSeverance.tsx")
};
