import type { PreviewResourceDefinition } from './types';

export const patientFamilyPreviewDefinitions: Record<string, PreviewResourceDefinition> = {
  Diseases: {
    resource: 'Diseases',
    title: 'Patient Conditions',
    singular: 'condition',
    description: 'Track a diagnosed or reported health condition associated with a patient.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'conditionName', label: 'Condition name', type: 'text', required: true },
      { key: 'diagnosedOn', label: 'Date identified', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Resolved', 'In review'] },
      { key: 'notes', label: 'Clinical notes', type: 'textarea' },
    ],
    columns: ['patientId', 'conditionName', 'diagnosedOn', 'status'],
  },
  EhrPatients: {
    resource: 'EhrPatients',
    title: 'EHR Patient Profiles',
    singular: 'EHR profile',
    description: 'Review a patient’s EHR linkage, medical history, language preference, and consent status.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'medicalHistory', label: 'Medical history summary', type: 'textarea' },
      { key: 'ehrStatus', label: 'EHR status', type: 'select', required: true, options: ['Active', 'Pending review', 'Inactive'] },
      { key: 'preferredLanguage', label: 'Preferred language', type: 'select', options: ['English', 'Spanish', 'Other'] },
      { key: 'consentOnFile', label: 'Consent on file', type: 'checkbox' },
    ],
    columns: ['patientId', 'ehrStatus', 'preferredLanguage', 'consentOnFile'],
  },
  FamilyModules: {
    resource: 'FamilyModules',
    title: 'Household Overviews',
    singular: 'household overview',
    description: 'Organize a household around its guarantor, member patient IDs, and shared contact details.',
    patientScoped: false,
    fields: [
      { key: 'householdName', label: 'Household name', type: 'text', required: true },
      { key: 'guarantorId', label: 'Guarantor patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'memberIds', label: 'Member patient ID numbers', type: 'textarea', required: true, help: 'Enter patient ID numbers separated by commas.' },
      { key: 'primaryContactName', label: 'Primary contact name', type: 'text' },
      { key: 'phone', label: 'Household phone', type: 'tel' },
      { key: 'email', label: 'Household email', type: 'email' },
      { key: 'streetAddress', label: 'Street address', type: 'text' },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'region', label: 'State / region', type: 'text' },
      { key: 'postalCode', label: 'Postal code', type: 'text' },
    ],
    columns: ['householdName', 'guarantorId', 'memberIds', 'phone', 'email'],
  },
  Guardians: {
    resource: 'Guardians',
    title: 'Patient Guardians & Caregivers',
    singular: 'guardian or caregiver',
    description: 'Record a caregiver’s relationship and contact details for a patient.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'guardianName', label: 'Guardian / caregiver name', type: 'text', required: true },
      { key: 'relationship', label: 'Relationship to patient', type: 'select', options: ['Parent', 'Guardian', 'Spouse / partner', 'Caregiver', 'Other'] },
      { key: 'phone', label: 'Phone number', type: 'tel' },
      { key: 'email', label: 'Email address', type: 'email' },
      { key: 'authorizedForCare', label: 'Authorized for care discussions', type: 'checkbox' },
      { key: 'notes', label: 'Additional details', type: 'textarea' },
    ],
    columns: ['patientId', 'guardianName', 'relationship', 'phone', 'email'],
  },
  MedicationPats: {
    resource: 'MedicationPats',
    title: 'Patient Medication Courses',
    singular: 'patient medication course',
    description: 'Document a medication prescribed or reported for an individual patient, including dose and schedule.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'medicationName', label: 'Medication name', type: 'text', required: true },
      { key: 'strength', label: 'Strength', type: 'text' },
      { key: 'dose', label: 'Dose per administration', type: 'text', required: true },
      { key: 'route', label: 'Route', type: 'select', options: ['Oral', 'Topical', 'Injection', 'Other'] },
      { key: 'frequency', label: 'Frequency / directions', type: 'text', required: true },
      { key: 'startedOn', label: 'Start date', type: 'date' },
      { key: 'stoppedOn', label: 'Stop date', type: 'date' },
      { key: 'active', label: 'Currently taking', type: 'checkbox' },
    ],
    columns: ['patientId', 'medicationName', 'dose', 'frequency', 'startedOn', 'active'],
  },
  Medications: {
    resource: 'Medications',
    title: 'Medication Reference',
    singular: 'medication reference',
    description: 'Maintain a readable medication reference with common strength and dosage-form details.',
    patientScoped: false,
    fields: [
      { key: 'medicationName', label: 'Medication name', type: 'text', required: true },
      { key: 'genericName', label: 'Generic name', type: 'text' },
      { key: 'strength', label: 'Common strength', type: 'text' },
      { key: 'dosageForm', label: 'Dosage form', type: 'select', options: ['Tablet', 'Capsule', 'Liquid', 'Cream / gel', 'Other'] },
      { key: 'route', label: 'Typical route', type: 'select', options: ['Oral', 'Topical', 'Injection', 'Other'] },
      { key: 'notes', label: 'Reference notes', type: 'textarea' },
    ],
    columns: ['medicationName', 'genericName', 'strength', 'dosageForm', 'route'],
  },
  PatientNotes: {
    resource: 'PatientNotes',
    title: 'Patient Notes',
    singular: 'patient note',
    description: 'Capture a dated note or follow-up reminder associated with a patient.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'noteDate', label: 'Note date', type: 'date', required: true },
      { key: 'noteType', label: 'Note type', type: 'select', options: ['Care coordination', 'Patient communication', 'Follow-up', 'Other'] },
      { key: 'subject', label: 'Subject', type: 'text', required: true },
      { key: 'noteText', label: 'Note', type: 'textarea', required: true },
      { key: 'followUpOn', label: 'Follow-up date', type: 'date' },
      { key: 'privateNote', label: 'Internal note', type: 'checkbox' },
    ],
    columns: ['patientId', 'noteDate', 'noteType', 'subject', 'followUpOn'],
  },
  PatientRaces: {
    resource: 'PatientRaces',
    title: 'Patient Race & Ethnicity',
    singular: 'race and ethnicity entry',
    description: 'Record patient-reported race and ethnicity information respectfully and consistently.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'race', label: 'Race', type: 'select', options: ['American Indian or Alaska Native', 'Asian', 'Black or African American', 'Native Hawaiian or Pacific Islander', 'White', 'Multiple races', 'Other', 'Prefer not to say'] },
      { key: 'ethnicity', label: 'Ethnicity', type: 'select', options: ['Hispanic or Latino', 'Not Hispanic or Latino', 'Other', 'Prefer not to say'] },
      { key: 'selfReported', label: 'Reported by patient', type: 'checkbox' },
      { key: 'notes', label: 'Additional context', type: 'textarea' },
    ],
    columns: ['patientId', 'race', 'ethnicity', 'selfReported'],
  },
  Patients: {
    resource: 'Patients',
    title: 'Patient Directory',
    singular: 'patient',
    description: 'Manage core patient identity, contact, address, and account status details.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'firstName', label: 'First name', type: 'text', required: true },
      { key: 'lastName', label: 'Last name', type: 'text', required: true },
      { key: 'dateOfBirth', label: 'Date of birth', type: 'date' },
      { key: 'gender', label: 'Gender', type: 'select', options: ['Female', 'Male', 'Non-binary', 'Another identity', 'Prefer not to say'] },
      { key: 'phone', label: 'Phone number', type: 'tel' },
      { key: 'email', label: 'Email address', type: 'email' },
      { key: 'streetAddress', label: 'Street address', type: 'text' },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'region', label: 'State / region', type: 'text' },
      { key: 'postalCode', label: 'Postal code', type: 'text' },
      { key: 'status', label: 'Patient status', type: 'select', required: true, options: ['Active', 'Inactive', 'Archived'] },
    ],
    columns: ['patientId', 'firstName', 'lastName', 'dateOfBirth', 'phone', 'status'],
  },
  PatFieldDefs: {
    resource: 'PatFieldDefs',
    title: 'Patient Custom Field Definitions',
    singular: 'custom field definition',
    description: 'Define a reusable patient-specific field label and the kind of information it collects.',
    patientScoped: false,
    fields: [
      { key: 'fieldName', label: 'Field name', type: 'text', required: true },
      { key: 'displayLabel', label: 'Display label', type: 'text', required: true },
      { key: 'fieldType', label: 'Input type', type: 'select', required: true, options: ['Text', 'Number', 'Date', 'Checkbox', 'Choice'] },
      { key: 'requiredForEntry', label: 'Required when entered', type: 'checkbox' },
      { key: 'choiceOptions', label: 'Choice options', type: 'textarea', help: 'For choice fields, enter one option per line.' },
      { key: 'helpText', label: 'Help text', type: 'textarea' },
    ],
    columns: ['fieldName', 'displayLabel', 'fieldType', 'requiredForEntry'],
  },
  PatFields: {
    resource: 'PatFields',
    title: 'Patient Custom Field Values',
    singular: 'custom field value',
    description: 'Store the value of a custom information field for an individual patient.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'fieldLabel', label: 'Custom field label', type: 'text', required: true },
      { key: 'value', label: 'Field value', type: 'textarea', required: true },
      { key: 'recordedOn', label: 'Recorded on', type: 'date' },
      { key: 'reviewRequired', label: 'Review required', type: 'checkbox' },
    ],
    columns: ['patientId', 'fieldLabel', 'value', 'recordedOn', 'reviewRequired'],
  },
  PatPlans: {
    resource: 'PatPlans',
    title: 'Patient Insurance Plans',
    singular: 'patient insurance plan',
    description: 'Track a patient’s insurance enrollment and the subscriber details needed for coverage review.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'planName', label: 'Plan name', type: 'text', required: true },
      { key: 'carrierName', label: 'Insurance carrier', type: 'text', required: true },
      { key: 'memberId', label: 'Member ID', type: 'text', required: true },
      { key: 'groupNumber', label: 'Group number', type: 'text' },
      { key: 'subscriberName', label: 'Subscriber name', type: 'text' },
      { key: 'subscriberRelationship', label: 'Subscriber relationship', type: 'select', options: ['Self', 'Spouse / partner', 'Parent', 'Other'] },
      { key: 'effectiveOn', label: 'Effective date', type: 'date' },
      { key: 'expiresOn', label: 'End date', type: 'date' },
      { key: 'active', label: 'Current plan', type: 'checkbox' },
    ],
    columns: ['patientId', 'planName', 'carrierName', 'memberId', 'effectiveOn', 'active'],
  },
  PatRestrictions: {
    resource: 'PatRestrictions',
    title: 'Patient Care Restrictions',
    singular: 'care restriction',
    description: 'Document a patient-specific care, communication, or access restriction and its review status.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'restrictionType', label: 'Restriction type', type: 'select', required: true, options: ['Care precaution', 'Communication preference', 'Access limitation', 'Other'] },
      { key: 'description', label: 'Restriction details', type: 'textarea', required: true },
      { key: 'startsOn', label: 'Start date', type: 'date' },
      { key: 'reviewOn', label: 'Review date', type: 'date' },
      { key: 'active', label: 'Currently active', type: 'checkbox' },
      { key: 'enteredBy', label: 'Entered by', type: 'text' },
    ],
    columns: ['patientId', 'restrictionType', 'description', 'startsOn', 'reviewOn', 'active'],
  },
  Pharmacies: {
    resource: 'Pharmacies',
    title: 'Pharmacy Directory',
    singular: 'pharmacy',
    description: 'Maintain pharmacy contact and location details for patient coordination.',
    patientScoped: false,
    fields: [
      { key: 'pharmacyName', label: 'Pharmacy name', type: 'text', required: true },
      { key: 'phone', label: 'Phone number', type: 'tel', required: true },
      { key: 'fax', label: 'Fax number', type: 'tel' },
      { key: 'email', label: 'Email address', type: 'email' },
      { key: 'streetAddress', label: 'Street address', type: 'text', required: true },
      { key: 'city', label: 'City', type: 'text', required: true },
      { key: 'region', label: 'State / region', type: 'text' },
      { key: 'postalCode', label: 'Postal code', type: 'text' },
      { key: 'preferred', label: 'Preferred pharmacy', type: 'checkbox' },
    ],
    columns: ['pharmacyName', 'phone', 'city', 'region', 'postalCode'],
  },
  Popups: {
    resource: 'Popups',
    title: 'Patient Alerts',
    singular: 'patient alert',
    description: 'Create a concise patient-specific alert for staff to review during care or coordination.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'alertTitle', label: 'Alert title', type: 'text', required: true },
      { key: 'message', label: 'Alert message', type: 'textarea', required: true },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Routine', 'Important', 'Urgent'] },
      { key: 'showUntil', label: 'Show through', type: 'date' },
      { key: 'active', label: 'Alert is active', type: 'checkbox' },
    ],
    columns: ['patientId', 'alertTitle', 'priority', 'showUntil', 'active'],
  },
  Recalls: {
    resource: 'Recalls',
    title: 'Patient Recall Schedule',
    singular: 'patient recall',
    description: 'Schedule a patient recall with a target date, recall category, and follow-up status.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'recallType', label: 'Recall type', type: 'text', required: true },
      { key: 'dueOn', label: 'Recall date', type: 'date', required: true },
      { key: 'status', label: 'Recall status', type: 'select', required: true, options: ['Due', 'Contacted', 'Scheduled', 'Completed', 'Deferred'] },
      { key: 'lastContactedOn', label: 'Last contacted', type: 'date' },
      { key: 'notes', label: 'Follow-up notes', type: 'textarea' },
    ],
    columns: ['patientId', 'recallType', 'dueOn', 'status', 'lastContactedOn'],
  },
  RecallTypes: {
    resource: 'RecallTypes',
    title: 'Recall Type Catalog',
    singular: 'recall type',
    description: 'Set up reusable recall categories with a suggested interval and staff-facing guidance.',
    patientScoped: false,
    fields: [
      { key: 'typeName', label: 'Recall type name', type: 'text', required: true },
      { key: 'intervalMonths', label: 'Suggested interval (months)', type: 'number', min: 1, max: 120, step: '1' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'active', label: 'Available for use', type: 'checkbox' },
    ],
    columns: ['typeName', 'intervalMonths', 'description', 'active'],
  },
  RxPats: {
    resource: 'RxPats',
    title: 'Patient Prescriptions',
    singular: 'prescription',
    description: 'Record a patient prescription with its prescribed dose, quantity, directions, and dates.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'medicationName', label: 'Medication name', type: 'text', required: true },
      { key: 'strength', label: 'Medication strength', type: 'text' },
      { key: 'dose', label: 'Prescribed dose', type: 'text', required: true },
      { key: 'directions', label: 'Directions for use', type: 'textarea', required: true },
      { key: 'quantity', label: 'Quantity', type: 'number', min: 0, step: '1' },
      { key: 'refills', label: 'Refills', type: 'number', min: 0, max: 99, step: '1' },
      { key: 'prescribedOn', label: 'Prescribed date', type: 'date' },
      { key: 'expiresOn', label: 'Expiration date', type: 'date' },
      { key: 'pharmacyName', label: 'Pharmacy', type: 'text' },
    ],
    columns: ['patientId', 'medicationName', 'dose', 'quantity', 'refills', 'prescribedOn'],
  },
  Vitalsigns: {
    resource: 'Vitalsigns',
    title: 'Patient Vital Signs',
    singular: 'vital sign reading',
    description: 'Capture a patient’s dated vital sign measurements with explicit units.',
    patientScoped: true,
    fields: [
      { key: 'patientId', label: 'Patient ID number', type: 'number', required: true, min: 1, step: '1' },
      { key: 'measuredOn', label: 'Measurement date', type: 'date', required: true },
      { key: 'heightCm', label: 'Height (cm)', type: 'number', min: 0, max: 300, step: '0.1' },
      { key: 'weightKg', label: 'Weight (kg)', type: 'number', min: 0, max: 1000, step: '0.1' },
      { key: 'temperatureC', label: 'Temperature (°C)', type: 'number', min: 25, max: 45, step: '0.1' },
      { key: 'systolicMmhg', label: 'Systolic blood pressure (mmHg)', type: 'number', min: 0, max: 300, step: '1' },
      { key: 'diastolicMmhg', label: 'Diastolic blood pressure (mmHg)', type: 'number', min: 0, max: 200, step: '1' },
      { key: 'pulseBpm', label: 'Pulse (bpm)', type: 'number', min: 0, max: 300, step: '1' },
      { key: 'respiratoryRatePerMin', label: 'Respiratory rate (breaths/min)', type: 'number', min: 0, max: 100, step: '1' },
      { key: 'oxygenSaturationPercent', label: 'Oxygen saturation (%)', type: 'number', min: 0, max: 100, step: '1' },
    ],
    columns: ['patientId', 'measuredOn', 'heightCm', 'weightKg', 'temperatureC', 'systolicMmhg', 'diastolicMmhg', 'pulseBpm'],
  },
};